package com.example.shoppinglist.data.db

import androidx.room.Database
import androidx.room.RoomDatabase
import com.example.shoppinglist.data.entity.ShoppingListItem

@Database(
    entities = [ShoppingListItem::class],
    version = 1,
    exportSchema = false
)
abstract class ShoppingListDatabase: RoomDatabase() {

    abstract fun getShoppingListDao(): ShoppingListDao  //a concrete implementation of the Interface gets generated by Room
}